### ISSUE TITLE
 sourcemap error with lazy route 

### ISSUE THREAD

**Issue by rodmar35** [riot/parcel-transformer-riot#22]
Hello @GianlucaGuarini, thanks for your parcel transformer.

I'v installed riot with parcel template via npm

have you ever managed to make parcel-transformer-riot work with lazy route? When I try I have an error 

`🚨 Parcel encountered errors : @riotjs/parcel-transformer-riot: [parcel-sourcemap] Source out of range`

```Error: [parcel-sourcemap] Source out of range
    at NodeSourceMap.addVLQMap (.........../node_modules/@parcel/source-map/dist/node.js:37:28)
    at Object.transform (.........../node_modules/@riotjs/parcel-transformer-riot/index.js:59:28)
    at async Transformation.runTransformer (.........../node_modules/@parcel/core/lib/Transformation.js:617:5)
    at async Transformation.runPipeline (.........../node_modules/@parcel/core/lib/Transformation.js:366:36)
    at async Transformation.runPipelines (.........../node_modules/@parcel/core/lib/Transformation.js:244:40)
    at async Transformation.run (.........../node_modules/@parcel/core/lib/Transformation.js:170:19)
    at async Child.handleRequest (.........../node_modules/@parcel/workers/lib/child.js:217:9)
```

My code in app.riot

``` <script>
    import reload from '@riotjs/hot-reload'
    import { Router, Route, route, toRegexp, match } from '@riotjs/route'
    import lazy from '@riotjs/lazy'
    import Loader from './components/includes/loader/loader.riot' 
    import NotFound from '../../../pages/not-found.riot' 
    import pages from '../../../pages' 
    export default {
      components: {
        Router,
        Route,
        NotFound,
        Home: lazy(Loader, () => import('../../../pages/home.riot')),
        About: lazy(Loader, () => import('../../../pages/about.riot')),
      }
    }
  </script>```

thank you in advance for your advice.
rodmar35

**Comment by GianlucaGuarini** [comment]
hi @rodmar35 thank you for this issue. A workaround could be to compile without sourcemaps:
`parcel build index.html --no-source-maps`

I will ask for help here https://github.com/parcel-bundler/source-map

**Comment by GianlucaGuarini** [comment]
the issue was solved by updating the project using the latest parcel version https://github.com/riot/parcel-transformer-riot/pull/24
